path = "./hoge.h"
header = """
#ifndef HOGE_H
#define HOGE_H
/***************************************************************************
    File Name:      ${FILE_NAME}
    Author:         MoriokaReimen
    description:    Configuration for Super Cool Software
    Data:           ${DATE_TIME}
***************************************************************************/
"""

footer = """
#endif
/* End of ${FILE_NAME} */
"""

[[configs]]
symbol = "DEBUG"
description = "My Config"
detail = "my first config"
enable = true

[[configs]]
symbol = "DEBUG2"
description = "My Config2"
detail = "my second config"
enable = false

[[val_configs]]
symbol = "DEBUG"
description = "My Config"
detail = "my first config"
value = 1.5
enable = true

[[val_configs]]
symbol = "DEBUG2"
description = "My Config2"
detail = "my second config"
value = 30
enable = false

